=head1 TO DO

=head2 Modules

Look at L<App::YTLD> instead of rolling your own (or stealing from jwz)

=head2 HTML CLIENT

=over 4

=item *

Implement simple HTML client with Server Side Events

  <html>
  <body>
  <video id="content_video"></video>
  <audio id="content_video"></audio>
  </body>
  </html>

  #content_video.src= "http://remote.source.mp4"
  #content_video.play()

=item *

Add .m3u parser for audio streaming

=item *

Add serving of playlist by setting both

  $renderer->setAVTransportURI(CurrentURI => $url);
  $renderer->setNextAVTransportURI(CurrentURI => $url);

=back

=cut